### ISSUE TITLE
Wrong TimeZone conversion

### ISSUE THREAD

**Issue by kamuffe** [stefanuebe/vaadin_fullcalendar#110]
### Bug Description

TimeZones in client and server JVM might differ most of the time. FC converts the server time before rendering the events to the users browser timezone (local) or to the desired one if set explicitly.
This requires that the time passed to FC client is in UTC.
For this case the getStartTimezone and getEndTimezone are in place to get the timezone from client.
And this is the issue.
When getting a time/date with LocalDateTime.now() the time is in the timezone the server is running on. This is not always UTC.
getStartTimezone not gets the client timezone or falls back to UTC. that causes that the server time is interpreted as UTC and not converted to it.
This causes a shift of the events in calender. 

This can be tested with the following sample code.

### Example Code

```
package test;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;

public class TimeZone
{
	
	public static void main( String[] args )
	{
		/*
		 * make sure JVM runs in Berlin time
		 */
		System.setProperty( "user.timezone", "Europe/Berlin" );
		
		System.out.println( "JVM running in:" );
		System.out.println( ZoneId.systemDefault() );
		System.out.println();
		
		/*
		 * working
		 */
		ZoneId utc = ZoneId.of( "UTC" );
		ZoneId berlin = ZoneId.of( "Europe/Berlin" );
		LocalDateTime ldt = LocalDateTime.of( 2021, 10, 21, 16, 0 );// implicit Berlin SummerTime as of 27.10.
		
		// FC code from: org.vaadin.stefan.fullcalendar.Timezone.convertToUTC(LocalDateTime)
		Instant instant = ldt.toInstant( berlin.getRules().getOffset( ldt ) );
		
		System.out.println( "Working: correct convert" );
		System.out.println( "LocalDateTime: " + ldt );
		System.out.println( "Instant:       " + instant.toString() + " <= passed to FC client. Correct UTC time can be handled correctly in client." ); // 2021-10-21T14:00:00Z
		
		/*
		 * not working
		 * German time is interpreted as UTC and that causes the 2h (summer time) and 1h (normal time) diff
		 * This is because the converting timezone is obtained from Calendar (Client Side or UTC fallback) and not from the running JVM on
		 * the
		 * Server.
		 * LocalDate.now uses System Timezone and therefore the UTC convert method have to use this same TimeZone.
		 */
		ldt = LocalDateTime.of( 2021, 10, 21, 16, 0 );// implicit Berlin SummerTime as of 27.10.
		
		/*
		 * FC code from:org.vaadin.stefan.fullcalendar.Timezone.convertToUTC(LocalDateTime)
		 * just interprets berlin time as UTC. FC now receives this interpreted time and converts it to the client timezone which does the
		 * shift.
		 */
		instant = ldt.toInstant( utc.getRules().getOffset( ldt ) );//
																	//
		
		System.out.println();
		System.out.println( "Not Working:" );
		System.out.println( "LocalDateTime: " + ldt );
		System.out.println( "Instant:       " + instant.toString() + " <===== Interpreted as UTC but is acually berlin time!!!" ); // 2021-10-21T14:00:00Z
	}
	
}

```

### Solution

Use server / JVM timezone fo conversation in org.vaadin.stefan.fullcalendar.Entry.getStartTimezone() and org.vaadin.stefan.fullcalendar.Entry.getEndTimezone()

**Comment by stefanuebe** [comment]
Changing the "getXyzTimezone" to use the server timezone is critical, since it is also used to convert any timestamps coming from the client (see Entry#update). This might need some additional changes on how the calendar times behave on client and server.

It is correct, that the server side usage of the localized timestamp methods may make no sense here, but we cannot simply change the getTimezone for that use case as these methods are more or less convenience/backward-compatibility methods to cover the internally used Instand methods.

Have you tested, how entry changes (e.g. by drag and drop) apply to the server side after your changes? When the server timezone is for instant PT and the user is in Berlin Time, this might lead to some interest effects. A different solution would be to simply apply the Timezone.getSystem() inside the localized timestamp methods and leave the "getXyzTimezone" untouched. Also methods like "setStart(LocalDateTime, Timezone)" might make no sense.

**Comment by kamuffe** [comment]
I'll check this out and make a new suggestion :)

Indeed a test failed and there was some strage behavior when dragging the appointments.

Thanks a lot.

**Comment by stefanuebe** [comment]
@kamuffe 

Please review the changes made in the branch "timezone_overhaul". I will roll back the master for now until the issues are fixed there. Please use that branch for any upcoming fixes for now.

**Comment by stefanuebe** [comment]
(I just had to force push the timezone_overhaul branch - if you checked it out before, please make sure to update now before continuing)

**Comment by stefanuebe** [comment]
@kamuffe had you time to review and test the changes, if they fit your scenario?

**Comment by stefanuebe** [comment]
Fixed with version 3.2.0.

**Comment by stefanuebe** [comment]
Hi @kamuffe after thinking a bit about this change the question came into my mind, why to apply the server timezone at all or to be more concrete, why to apply the server time zone to the Instant to create a LocalDateTime. I know, that I applied the timezone in previous versions, but this seems to be simply wrong since LocalDateTime does not have a timezone and therefore should simply represent the UTC time, right?

**Comment by christophkarmowski** [comment]
@stefanuebe Sorry for the delay.
I will check the new version. But first I have to migrate. Lukily you provided a wiki with all infos :) Thanks a lot for this work and the good documentation.

Best, Kamuffe

**Comment by kamuffe** [comment]
@stefanuebe Sorry for the delay.
I will check the new version. But first I have to migrate. Lukily you provided a wiki with all infos :) Thanks a lot for this work and the good documentation.

Best, Kamuffe
