### ISSUE TITLE
Why does the Scheduler add-on requires a licenseKey?

### ISSUE THREAD

**Issue by simasch** [stefanuebe/vaadin_fullcalendar#114]
According to https://fullcalendar.io/pricing only few features require a licencse.

Why are free features in the Scheduler add-on that don't require a license?

**Comment by aetasoul** [comment]
Please check the wiki https://github.com/stefanuebe/vaadin_fullcalendar/wiki/FullCalendar-Scheduler-License

**Comment by simasch** [comment]
@aetasoul Thanks for the pointer. I couldn't find this information.

**Comment by simasch** [comment]
@aetasoul But if I check the premium features I only see this:

https://fullcalendar.io/docs/premium

So for example addTimeslotsSelectedSchedulerListener shouldn't be premium, right?

**Comment by aetasoul** [comment]
`addTimeslotsSelectedSchedulerListener` use the `TimeslotsSelectedSchedulerEvent`class that extends `TimeslotsSelectedEvent ` which is part of the Calendar that use the [select callback](https://fullcalendar.io/docs/select-callback).

The `TimeslotClickedSchedulerEvent` is inside the Calendar scheduler because we need to manage the resources. 

As you can see on this page https://fullcalendar.io/docs/select-callback the `selectionInfo ` object has a property called resource with this description:

> Resource object. If the current view is a resource view, this is the Resource object that was selected. This is only available when using one of the resource plugins.

The usage of `addTimeslotsSelectedSchedulerListener` is not under the premium but the [resource object](https://fullcalendar.io/docs/resource-object) requires premium, so technically you need the premium to use the resource property.

**Comment by simasch** [comment]
Now I understand!

Thanks a lot for the clarification @aetasoul

**Comment by aetasoul** [comment]
No problem 😊
