### ISSUE TITLE
setEntryContentCallback - can't read properties of style.

### ISSUE THREAD

**Issue by jimorm** [stefanuebe/vaadin_fullcalendar#149]
### Bug Description
Hi all,

I try to customise event's style in calendar, and use the piece of code from samples : 

calendar.setEntryContentCallback("" +
	"function(info) {" +
        "   info.el.style.color = 'red';" +
        "   return info.el; " +
        "}"
);

I obtain an error : 
![image](https://user-images.githubusercontent.com/105065349/167371998-40471423-9d2a-4ef7-9899-613df11f715e.png)

I found multiple syntax, and spent hours to get it work without success ! 
Could someone help ?

**Comment by aetasoul** [comment]
In this case the solution that I adopt to find the problem is to print and dig into the info object.

```
calendar.setEntryContentCallback("" +
"function(info) {" +
" console.log(info);" +
"}"
);
```

The examples are not up to date, as you can read [here](https://fullcalendar.io/docs/event-render-hooks) in the **Argument** section the _el_ object is only avaiable with  `eventDidMount `and `eventWillUnmount`

To use the _el_ object and change the syle you need to use: `setEntryDidMountCallback`

**Comment by aetasoul** [comment]
Wiki page is not up to date

**Comment by jimorm** [comment]
Aetasoul, I want to marry you :)
Perfect !! And answer so quicly !!  
Thank you very much !
