### ISSUE TITLE
Error when using initialOptions (eventContent)

### ISSUE THREAD

**Issue by lipisak** [stefanuebe/vaadin_fullcalendar#175]
Hello,
I have found a possible issue in vaadin_fullcalendar.

### Description
If I use custom initialOptions in FullCalendarBuilder with `eventContent` (set by JsonObject) it works correctly when calendar is added into view. But if I remove and add back the same instance into view (ie. `div.remove(calendar);`, `div.add(calendar);`) it throws javascript client error and calendar doesn't work anymore.

If I remove the initialOptions the calendar works as expected.

It happens with recent version (6.0.2) but also prior versions. 
It happens in Chrome/Safari/Edge
It happens with JDK 11 also with JDK 17
It happens with Vaadin 14.10.7

Error is as follows:
`Unhandled Promise Rejection: TypeError: value.call is not a function. (In 'value.call(this._calendar, info)', 'value.call' is undefined)`

### Screenshots
<img width="1021" alt="Snímek obrazovky 2023-09-26 v 17 13 10" src="https://github.com/stefanuebe/vaadin_fullcalendar/assets/2478417/60595a3c-e281-40c4-8f95-490ddd916b99">

Could you please take a look into this?

**Comment by aetasoul** [comment]
Can you share the code to replicate the problem? Thank you

**Comment by lipisak** [comment]
I am attaching view with all necessary code
[AboutView.zip](https://github.com/stefanuebe/vaadin_fullcalendar/files/12729691/AboutView.zip)

If you need the entire project, I can send it to you.

**Comment by aetasoul** [comment]
Thank you! I'll dig into it and let you know as soon as possible!

**Comment by stefanuebe** [comment]
@aetasoul 
The reason is, that on reattachment, the Java side tries to restore the state (options, view, date) on the client side, since the client side will be recreated new. Since the client side calendar instance exists already at that time, setting the eventContent callback afterwards will not work (as the errors indicate). 

So a potential fix (note for us) would be, that we assure, that the server state is transported to the client before the client instance is created or in case of "restoreStateFromServer" it needs to recreate the client instance again - but the second part I would see only as a fallback, since that would lead to a double creation which I would like to avoid.

@lipisak 
The only workaround I can provide up to the fix is to recreate also the server side instance on reattachment. This should not be a huge issue since at least entries are nowadays fetched per shown period and not all at once. Also setting the view and date is relatively cheap for the FC so the only effort is to redo the construction work and setup.

**Comment by lipisak** [comment]
@stefanuebe 
thank you for your effort, I will try to "recreate" the calendar from scratch everytime the user "returns" to it by saving all the parameters that were used last time. The question is if there is a possibility that you can make a fix you suggested to aetasoul in "near" future or not. I could make a "simplier" fix if I knew that you will be able to fix it 🙂

**Comment by stefanuebe** [comment]
Short resume of the current state. I had some time this morning and atM it looks like it is much less effort then I had estimated. Might be that I can push a fix today, so maybe wait a bit if you have the time :)

**Comment by stefanuebe** [comment]
Please recheck with 6.0.3.

**Comment by lipisak** [comment]
Thank you very much @stefanuebe and @aetasoul 🙏. It worked like a charm - and as I saw - fix was to remove a code instead of addition 😄 nice.
