### ISSUE TITLE
Add info about how to migrate correctly from V13 to V14

### ISSUE THREAD

**Issue by masbaehr** [stefanuebe/vaadin_fullcalendar#25]
Hi, could you please add some information about how to migrate from the old fullcalendar variant? (To use Vaadin14 without compatibility mode)  

![image](https://user-images.githubusercontent.com/38694044/66633069-3dabad00-ec0a-11e9-9243-ad9a8fa3a5ad.png)

I did this but im not sure yet if this is the correct version which reflects the latest changes made here?

**Comment by stefanuebe** [comment]
The version you posted is the correct one (beside that the RC version is higher). Don't know when or if I have time to write some migration guide. When switching to V14 npm and using the new version it should work out of the box (beside some small api changes here and there).

**Comment by masbaehr** [comment]
Yea, i've already changed the obvoious API changes, but I'm getting a lot of errors like this:

(anonymous) @ client-122CE29AC0B9685B4DC485343E774096.cache.js:585
client-122CE29AC0B9685B4DC485343E774096.cache.js:195 (TypeError) : $0.setOption is not a function

Now i'm trying to figure out what went wrong :)
Is setOptions still supported?

**Comment by stefanuebe** [comment]
setOption is still supported. Please try following: add the goal `build-frontend` to the vaadin plugin goals and recompile the project. This will resolve npm dependencies at build time instead of runtime and should properly load the transitive dependencies of the addon. Might be related to them, that this is missing.
