### ISSUE TITLE
New features request

### ISSUE THREAD

**Issue by emattaboni** [stefanuebe/vaadin_fullcalendar#28]
Hi,
  we're interested in scheduler extension (for vaadin) for commercial use but we're missing some features.

For our project we would need:

1. event overlap from vaadin with the option to enable for foreground and background event overlap separately (eg. when enabled for background and not for foreground can put foreground events only outside background event areas but can put foreground events in same time slots);

2. time range view: option to set start date and end date on some views like timelines and resource timelines.

A nice to have would be:

- the option to enable overlap for foreground by resources in calendar view (eg. when option enabled can put foreground events in same time slots only if not linked to same resource);

- the option to link more than one resource to the same event;

- the option to merge the background events in inverse mode (if I add two they do not merge but they overlap).

Let us know if those features are feasable.

Thanks,
  Emanuele

**Comment by stefanuebe** [comment]
Hi Emanuele,

thanks for your interest in the addon. First to say, the commercial part of this addon is not the Vaadin integration, but the Scheduler library used as a basis, as you can see here: https://fullcalendar.io/license/premium
That means you need to contact the Full Calendar authors regarding commercial use.

A) About the must have features you requested:
1. It is possible to set a custom overlap behavior for an entry. This has not yet been implemented in Java, but you can simply adopt it yourself by creating a subclass of Entry (or in your case better ResourceEntry), add the property for overlap and override the `toJson` method, so that the attribute gets send to the client.

See https://fullcalendar.io/docs/event-object for info on the overlap.

I will surely integrate it in future but without any promised date at this time.

2. I'm not sure about that point. You mean a min and max date, so that for instance the timeline cannot go before 2019 or similar? If that's the case, that logic you'll have to program into your UI logic. The time line itself always displays a specific period range (e.g. a month) and switching between months is done by Vaadin buttons. Simply disable the `next` or `previous` button, when reaching the limit.

B) The nice to have features:
1. I'm not sure what you mean by that.
2. That should be working already, by using addResources(Collection)
3. Might be doable by adding the same group ID to the entries as explained here  https://fullcalendar.io/docs/background-events. Since `groupId` is also not yet there as a property, you could workaround that by extending the class as described in A1

**Comment by stefanuebe** [comment]
Todo: Integrate all missing properties from the FC client side event model into the server side (like `groupId` or `overlap`)

**Comment by emattaboni** [comment]
Hi Stefan,
  thanks for your quick reply.

A) Must have:
1. Ok, clear, thanks;
2. What I mean is, for example, show only 10 days in resource timeline month view. I think is doable setting this properties in the calendar:

```
  defaultView: 'resourceTimelineFourDays',
  views: {
    resourceTimelineFourDays: {
      type: 'resourceTimeline',
      duration: { days: 4 }
    }
  }
```
Can this be done from java?

B) Nice to have:
1. make events not overlappable if they're related to same resource(s) (like reservation of items: if one resource is reserved for an event (assigned to that event), another event with same resource can't be in same time slots);

2. Sorry, my fault... was using setResource instead...

3. Thanks, I'll try.

Thanks again,
  Emanuele

**Comment by FrogDevelopper** [comment]
Hi,

I, too, would like to display a 4-days view, like explained here [Custom Views via Settings](https://fullcalendar.io/docs/custom-view-with-settings)
`var calendar = new Calendar(calendarEl, {
  defaultView: 'timeline', // the name of a generic view
  duration: { days: 3 }
});`

How can we achieve it from Java ?
Is the `setOption` the way to do it ?
But, on the documentation (Get/Set Option)[https://fullcalendar.io/docs/dynamic-options], it is written:
> It is not currently possible to set View-Specific Options in this manner.

**Comment by FrogDevelopper** [comment]
FYI, I've be able to tinker the FullCalendar to display a custom view by following the [Creating a subclass of FullCalendar for custom mods](https://github.com/stefanuebe/vaadin_fullcalendar#creating-a-subclass-of-fullcalendar-for-custom-mods)

/!\ take attention on the path for the files !!

1. create  _resources/META-INF/resources/frontend/src/my-calendar.js_
```javascript
import {FullCalendar} from '../full-calendar';

export class MyCalendar extends FullCalendar {
  _createInitOptions() {
    const options = super._createInitOptions();
    options.defaultView = 'timeGridThreeDays';

    options.views = {
      timeGridThreeDays: {
        type: 'timeGrid',
        dayCount: 3,
        weekNumbers: false
      }
    };

    options.firstDay = 1
    options.snapDuration = '00:15';

    return options;
  }
}

customElements.define('my-calendar', MyCalendar);
```
2. Then create your Java class:
```java
import com.vaadin.flow.component.Tag;
import com.vaadin.flow.component.dependency.JsModule;
import org.vaadin.stefan.fullcalendar.FullCalendar;

@Tag("my-calendar")
@JsModule("./src/my-calendar.js")
public class MyCalendar extends FullCalendar {

    public MyCalendar() {
        super();
    }
```
3. use it like you'll use any other Vaadin Component
```java
var calendar = new MyCalendar();
...
```

**Comment by stefanuebe** [comment]
You can pass custom initial options with the upcoming version 2.3.0. There you can define your own view options initially (plus all other needed or necessary options). I will close this issue for now, if there are any additional needs, that are not solvable by using custom initial options, please open a new issue, so that the description and requirements are clear to resolve.
