### ISSUE TITLE
Not able to format time using slotLabelFormat

### ISSUE THREAD

**Issue by rodrigueztjose** [stefanuebe/vaadin_fullcalendar#54]
When i'm trying to format time in 24 hour format using slotLabelFormat, i'm getting an error showing i.cmdFormatter is not a function.

calendar.setOption("slotLabelFormat", "hour12:false");

On previous version (before vaadin 14) was working fine.

**Comment by stefanuebe** [comment]
I guess, that the old FC library (3.9) interpreted single object strings as the given above and the new one (4.4.0), that is used now, does not.

However, you can simply set the options as a JsonObject, which will then be interpreted.

Be aware, that setting this will overwrite the existing settings, so you have to include the default values, too, otherwise it will be formatted in a strange, unwanted way.

For you example, the code should look like the following (defaults are taken from here https://fullcalendar.io/docs/slotLabelFormat):

```
        JsonObject jsonSlotLabelFormat = Json.createObject();

        jsonSlotLabelFormat.put("hour12", true);
        jsonSlotLabelFormat.put("hour", "numeric");
        jsonSlotLabelFormat.put("minute", "2-digit");
        jsonSlotLabelFormat.put("omitZeroMinute", true);
        jsonSlotLabelFormat.put("meridiem", "short");

        calendar.setOption("slotLabelFormat", jsonSlotLabelFormat);
```

**Comment by rodrigueztjose** [comment]
thanks Stefan!

**Comment by Deeksha-moni** [comment]
hi, I am facing the same issue, but how to wrap this jsonObject in Full Calendar
